name: Deploy Three.js Showcase

permissions:
  contents: write 
  pages: write     

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      # Build Haunted House
      - name: Install dependencies (Haunted House)
        working-directory: 11-haunted-house
        run: bun install

      - name: Build Haunted House
        working-directory: 11-haunted-house
        run: bun run build
        env:
          OUT_DIR: './dist'
          BASE: './'  # Use relative paths

      # Add more projects here as needed
      # - name: Install dependencies (Project 2)
      #   working-directory: 12-another-project
      #   run: bun install
      #
      # - name: Build Project 2
      #   working-directory: 12-another-project
      #   run: bun run build

      # Prepare public directory structure
      - name: Prepare deployment directory
        run: |
          mkdir -p public/projects
          cp index.html public/
          cp -r 11-haunted-house/dist public/projects/11-haunted-house
          # cp -r 12-another-project/dist public/projects/12-another-project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
